development:
  adapter: postgresql
  encoding: utf8
  database: mydeployapp_development
  pool: 5
  host: localhost
  username: kapil
  password: kapil

test:
  adapter: postgresql
  encoding: utf8
  database: mydeployapp_test
  pool: 5
  host: localhost
  username: kapil
  password: kapil

production:
  adapter: postgresql
  encoding: utf8
  database: mydeployapp_production
  pool: 5
  host: localhost
  username: kapil
  password: kapil